export const PRODUCTS = [
  {
    id: 1,
    brand: "WAI by Vehon",
    brandId: "vehon",
    name: "WAI Home",
    subtitle: { de: "Indoor Feel Shoe", en: "Indoor feel shoe" },
    price: 169,
    color: { de: "Indigo", en: "Indigo" },
    material: "IVIVI Barefoot Textile",
    category: { de: "Feel Shoes", en: "Feel shoes" },
    image: "/wai_front.jpeg",
    hoverImage: "/wai_behind.jpeg",
    tag: { de: "Signature", en: "Signature" },
    fit: "contain",
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43", "44", "45"],
    description: {
      de: "Ein leichter Feel Shoe für Zuhause, das Studio und alle Momente dazwischen. Flexibel, atmungsaktiv und bewusst reduziert konstruiert.",
      en: "A lightweight feel shoe for home, the studio and every moment in between. Flexible, breathable and deliberately reduced.",
    },
  },
  {
    id: 2,
    brand: "WAI by Vehon",
    brandId: "vehon",
    name: "WAI Travel",
    subtitle: { de: "Packable Loafer", en: "Packable loafer" },
    price: 179,
    color: { de: "Deep Navy", en: "Deep navy" },
    material: "Flexible Textile Upper",
    category: { de: "Feel Shoes", en: "Feel shoes" },
    image: "/wai1_front.jpeg",
    hoverImage: "/wai1_behind.jpeg",
    tag: { de: "Travel", en: "Travel" },
    fit: "cover",
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    description: {
      de: "Gemacht für Wege, Wartezeiten und leichte Routinen unterwegs. Die flexible Konstruktion lässt sich flach verstauen und bleibt stabil genug für den ganzen Tag.",
      en: "Made for journeys, waiting times and easy routines on the road. Its flexible construction packs flat while staying supportive all day.",
    },
  },
  {
    id: 3,
    brand: "WAI by Vehon",
    brandId: "vehon",
    name: "WAI Flex",
    subtitle: { de: "Barefoot Technology", en: "Barefoot technology" },
    price: 189,
    color: { de: "Blue Canvas", en: "Blue canvas" },
    material: "IVIVI Sole System",
    category: { de: "Feel Shoes", en: "Feel shoes" },
    image: "/wai2_front.jpeg",
    hoverImage: "/wai2_behind.jpeg",
    tag: { de: "Neu", en: "New" },
    fit: "cover",
    sizes: ["37", "38", "39", "40", "41", "42", "43", "44"],
    description: {
      de: "Die weiche, rollbare Sohle gibt dem Fuß Raum, ohne den Look eines klassischen Slippers zu verlieren. Ruhig im Ausdruck, technisch in der Substanz.",
      en: "The soft, rollable sole gives the foot room without losing the look of a classic slipper. Calm in expression, technical at heart.",
    },
  },
  {
    id: 4,
    brand: "WAI by Vehon",
    brandId: "vehon",
    name: "WAI Lounge",
    subtitle: { de: "Soft Everyday Slip-on", en: "Soft everyday slip-on" },
    price: 159,
    color: { de: "Washed Blue", en: "Washed blue" },
    material: "Soft-woven Textile",
    category: { de: "Feel Shoes", en: "Feel shoes" },
    image: "/wai3_front.jpeg",
    hoverImage: "/wai3_behind.jpeg",
    fit: "cover",
    sizes: ["36", "37", "38", "39", "40", "41", "42", "43"],
    description: {
      de: "Ein entspannter Slip-on für ruhige Innenräume, kurze Wege und Tage, an denen Komfort selbstverständlich sein soll.",
      en: "A relaxed slip-on for calm interiors, short walks and days when comfort should feel effortless.",
    },
  },
  {
    id: 6,
    brand: "Vehon",
    brandId: "vehon",
    name: "Duke Velvet",
    subtitle: { de: "Mocassino", en: "Moccasin" },
    price: 279,
    color: { de: "Nero", en: "Nero" },
    material: "Velvet",
    category: { de: "Mocassini", en: "Moccasins" },
    image: "/shop/products/vehon-duke-velvet-front.webp",
    hoverImage: "/shop/products/vehon-duke-velvet-side.webp",
    fit: "cover",
    sizes: ["39", "40", "41", "42", "43", "44", "45", "46"],
    description: {
      de: "Samtweicher Auftritt mit fester Haltung: der Duke in Velvet, mit eigens entwickelter Sohle für Halt, Leichtigkeit und Ruhe.",
      en: "A velvet-soft entrance with composure: the Duke in velvet, finished with a custom sole for grip, lightness and ease.",
    },
  },
  {
    id: 7,
    brand: "Vehon",
    brandId: "vehon",
    name: "Prince Loafer",
    subtitle: { de: "Tech-knit Loafer", en: "Tech-knit loafer" },
    price: 259,
    color: { de: "Nero", en: "Nero" },
    material: "3D Knit",
    category: { de: "Mocassini", en: "Moccasins" },
    image: "/shop/products/vehon-prince-front.webp",
    hoverImage: "/shop/products/vehon-prince-side.webp",
    tag: { de: "Neu", en: "New" },
    fit: "cover",
    sizes: ["39", "40", "41", "42", "43", "44", "45", "46"],
    description: {
      de: "Der Prince verbindet die Silhouette des klassischen Loafers mit gestricktem Obermaterial: leicht, flexibel und vollständig Made in Italy.",
      en: "The Prince combines a classic loafer silhouette with a knitted upper: light, flexible and entirely made in Italy.",
    },
  },
  {
    id: 8,
    brand: "Vehon",
    brandId: "vehon",
    name: "Velluto Nero",
    subtitle: { de: "Pantofola", en: "Velvet slipper" },
    price: 249,
    color: { de: "Nero", en: "Nero" },
    material: "Velvet",
    category: { de: "Pantofole", en: "Slippers" },
    image: "/shop/products/vehon-velluto-front.webp",
    hoverImage: "/shop/products/vehon-velluto-side.webp",
    fit: "cover",
    sizes: ["38", "39", "40", "41", "42", "43", "44", "45"],
    description: {
      de: "Die Pantofola für drinnen: Velvet, cleaner Spann und die Ruhe von Cashmere-Decken und Marmorböden.",
      en: "The indoor pantofola: velvet, a clean vamp and the quiet luxury of cashmere throws and marble floors.",
    },
  },
  {
    id: 12,
    brand: "Montechiaro",
    brandId: "montechiaro",
    name: "Pully Rosso",
    subtitle: { de: "Signature Knit Pullover", en: "Signature knit pullover" },
    price: 219,
    color: { de: "Rosso", en: "Rosso" },
    material: "Heavy Jacquard Knit",
    category: { de: "Strick", en: "Knitwear" },
    image: "/shop/pully-red-front.webp",
    hoverImage: "/shop/pully-red-side.webp",
    tag: { de: "Statement Knit", en: "Statement knit" },
    fit: "contain",
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: {
      de: "Schwerer Jacquard-Strick mit reliefartiger Struktur, geradem Schnitt und gerippten Bündchen. Ein italienisches Statement-Piece mit Haltung.",
      en: "Heavy jacquard knit with sculptural texture, a straight fit and ribbed trims. An Italian statement piece with composure.",
    },
  },
  {
    id: 13,
    brand: "Montechiaro",
    brandId: "montechiaro",
    name: "Pully Orange",
    subtitle: { de: "Signature Knit Pullover", en: "Signature knit pullover" },
    price: 219,
    color: { de: "Orange", en: "Orange" },
    material: "Jacquard Knit",
    category: { de: "Strick", en: "Knitwear" },
    image: "/shop/products/pully-orange/front.webp",
    hoverImage: "/shop/products/pully-orange/side.webp",
    gallery: [
      { src: "/shop/products/pully-orange/front.webp", fit: "contain" },
      { src: "/shop/products/pully-orange/side.webp", fit: "contain" },
      { src: "/shop/products/pully-orange/model.jpg", fit: "cover" },
      { src: "/shop/products/pully-orange/texture.jpg", fit: "cover" },
    ],
    tag: { de: "Neu", en: "New" },
    fit: "contain",
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: {
      de: "Strukturierter Jacquard-Strick mit markanten Farb- und Musterbahnen, geradem Schnitt und gerippten Bündchen.",
      en: "Textured jacquard knit with vivid colour and pattern panels, a straight fit and ribbed trims.",
    },
  },
  {
    id: 14,
    brand: "Montechiaro",
    brandId: "montechiaro",
    name: "Pully Dark",
    subtitle: { de: "Signature Knit Pullover", en: "Signature knit pullover" },
    price: 219,
    color: { de: "Dark Multicolor", en: "Dark multicolour" },
    material: "Jacquard Knit",
    category: { de: "Strick", en: "Knitwear" },
    image: "/shop/products/pully-dark/front.webp",
    hoverImage: "/shop/products/pully-dark/side.webp",
    gallery: [
      { src: "/shop/products/pully-dark/front.webp", fit: "contain" },
      { src: "/shop/products/pully-dark/side.webp", fit: "contain" },
      { src: "/shop/products/pully-dark/detail.jpg", fit: "cover" },
    ],
    tag: { de: "Neu", en: "New" },
    fit: "contain",
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: {
      de: "Dunkler Jacquard-Strick mit ausdrucksstarken Farb- und Musterbahnen, geradem Schnitt und gerippten Bündchen.",
      en: "Dark jacquard knit with vivid colour and pattern panels, a straight fit and ribbed trims.",
    },
  },
  {
    id: 15,
    brand: "Montechiaro",
    brandId: "montechiaro",
    name: "Pully Blue",
    subtitle: { de: "Signature Knit Pullover", en: "Signature knit pullover" },
    price: 219,
    color: { de: "Blue", en: "Blue" },
    material: "Jacquard Knit",
    category: { de: "Strick", en: "Knitwear" },
    image: "/shop/products/pully-blue/front.webp",
    hoverImage: "/shop/products/pully-blue/side.webp",
    gallery: [
      { src: "/shop/products/pully-blue/front.webp", fit: "contain" },
      { src: "/shop/products/pully-blue/side.webp", fit: "contain" },
      { src: "/shop/products/pully-blue/detail.jpg", fit: "cover" },
    ],
    tag: { de: "Neu", en: "New" },
    fit: "contain",
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: {
      de: "Jacquard-Strick in verschiedenen Blautönen mit reliefartigem Muster, geradem Schnitt und gerippten Bündchen.",
      en: "Jacquard knit in layered blue tones with a raised pattern, straight fit and ribbed trims.",
    },
  },
  {
    id: 16,
    brand: "Montechiaro",
    brandId: "montechiaro",
    name: "Pully Dark Blue",
    subtitle: { de: "Signature Knit Pullover", en: "Signature knit pullover" },
    price: 219,
    color: { de: "Dark Blue", en: "Dark blue" },
    material: "Jacquard Knit",
    category: { de: "Strick", en: "Knitwear" },
    image: "/shop/products/pully-dark-blue/front.webp",
    hoverImage: "/shop/products/pully-dark-blue/side.webp",
    gallery: [
      { src: "/shop/products/pully-dark-blue/front.webp", fit: "contain" },
      { src: "/shop/products/pully-dark-blue/side.webp", fit: "contain" },
    ],
    tag: { de: "Neu", en: "New" },
    fit: "contain",
    sizes: ["S", "M", "L", "XL", "XXL"],
    description: {
      de: "Dunkelblauer Jacquard-Strick mit kontrastierenden Musterbahnen, geradem Schnitt und gerippten Bündchen.",
      en: "Dark blue jacquard knit with contrasting pattern panels, a straight fit and ribbed trims.",
    },
  },
];
