const t = (de, en) => ({ de, en });

export const SERVICE_EMAIL = "office@nes-shop.at";
export const LEGAL_DRAFT_NOTE = t(
  "Entwurf: Unternehmensdaten und verbindliche Bedingungen sind noch nicht vollständig hinterlegt. Die markierten Angaben werden vor dem Verkaufsstart ergänzt und rechtlich geprüft.",
  "Draft: company details and binding terms are not yet complete. The marked details will be completed and legally reviewed before sales launch.",
);

export const SERVICE_PAGES = [
  {
    id: "contact", path: "/service/kontakt", group: "service", number: "01",
    label: t("Kontakt", "Contact"), title: t("Ein persönliches Gespräch.", "A personal conversation."),
    intro: t("Ein Modell im Blick, eine Frage zur Größe oder ein Anliegen zu Ihrer Auswahl? Schreiben Sie uns.", "A style in mind, a question about size or something about your selection? Get in touch."),
    sections: [
      { title: t("Direkt zu NES", "Directly to NES"), paragraphs: [t("Sie erreichen uns per E-Mail. Nennen Sie bei Produktfragen bitte Modell, Farbe und gewünschte Größe. Bei Fragen zu einem bereits vereinbarten Kauf hilft uns eine Bestell- oder Rechnungsnummer, sofern vorhanden.", "Reach us by email. For product questions, include the style, colour and preferred size. For an existing purchase, an order or invoice reference helps, if available.")], email: true },
      { title: t("Beratung, die bei Ihnen beginnt", "Advice that starts with you"), paragraphs: [t("Erzählen Sie uns, was Sie suchen und welche Passform Sie gerne tragen. Über unser Beratungsformular können Sie Ihre Frage direkt an NES senden.", "Tell us what you are looking for and the fit you enjoy wearing. Send your question directly to NES through our advice form.")], action: "advice" },
      { title: t("Weitere Kontaktdaten", "Further contact details"), facts: [[t("Telefon", "Phone"), t("[Telefonnummer ergänzen]", "[Add telephone number]")], [t("Postanschrift", "Postal address"), t("[Vollständige Anschrift ergänzen]", "[Add full postal address]")], [t("Erreichbarkeit", "Availability"), t("[Servicezeiten ergänzen]", "[Add service hours]")]], pending: true },
      { title: t("Für Händler und Marken", "For retailers and brands"), paragraphs: [t("Sie möchten unsere Kollektionen in Ihr Sortiment aufnehmen oder über eine Zusammenarbeit sprechen? Nutzen Sie unsere Partneranfrage.", "Would you like to stock our collections or discuss working together? Use our partnership enquiry.")], action: "trade" },
    ],
  },
  {
    id: "shipping", path: "/service/versand-zahlung", group: "service", number: "02",
    label: t("Versand & Zahlung", "Shipping & payment"), title: t("Gut zu wissen. Vorab.", "Good to know. Beforehand."),
    intro: t("Alles rund um Ihre Auswahl, die Lieferung und die Bezahlung an einem Ort.", "Your selection, delivery and payment, all in one place."),
    sections: [
      { title: t("So funktioniert es aktuell", "How it works today"), paragraphs: [t("Über den Warenkorb können Sie Ihre Auswahl unverbindlich anfragen. Wir bestätigen Verfügbarkeit, Versand und Gesamtpreis persönlich. Die Anfrage selbst ist keine Bestellung.", "Send a non-binding enquiry about the pieces in your bag. We personally confirm availability, shipping and the total price. The enquiry itself is not an order."), t("Der als Demo gekennzeichnete Checkout zeigt den geplanten Ablauf. Er löst keine Zahlung und keine Bestellung aus.", "The checkout marked as a demo previews the intended experience. It does not create an order or take payment.")] },
      { title: t("Lieferung", "Delivery"), facts: [[t("Lieferländer", "Delivery countries"), t("[Liefergebiet ergänzen]", "[Add delivery countries]")], [t("Versandkosten", "Shipping costs"), t("[Kosten je Lieferland ergänzen]", "[Add costs by destination]")], [t("Lieferzeit", "Delivery time"), t("[Lieferzeiten ergänzen]", "[Add delivery times]")], [t("Versandpartner", "Delivery partner"), t("[Versanddienstleister ergänzen]", "[Add delivery provider]")]], pending: true },
      { title: t("Preise und Bezahlung", "Prices and payment"), paragraphs: [t("Bei Artikeln mit „Preis auf Anfrage“ bestätigen wir den Preis im persönlichen Angebot. Die Darstellung im Demo-Checkout ist keine Zahlungsaufforderung.", "For items marked “Price on request”, we confirm the price in a personal offer. The demo checkout is not a payment request.")], facts: [[t("Zahlungsarten", "Payment methods"), t("[Verfügbare Zahlungsarten ergänzen]", "[Add supported payment methods]")], [t("Steuerhinweis", "Tax information"), t("[Zutreffenden Umsatzsteuerhinweis ergänzen]", "[Add applicable VAT information]")]], pending: true },
      { title: t("Noch eine Frage?", "Another question?"), paragraphs: [t("Wenn Sie ein bestimmtes Lieferziel oder einen Termin im Blick haben, klären wir die Möglichkeiten gerne vor Ihrer Anfrage.", "If you have a destination or a date in mind, we can discuss the options before you send your selection.")], action: "returns" },
    ],
  },
  {
    id: "returns", path: "/service/rueckgabe", group: "service", number: "03",
    label: t("Rückgabe & Widerruf", "Returns & withdrawal"), title: t("Falls es nicht passt.", "If it is not quite right."),
    intro: t("Hier finden Sie den Kontakt für Rückfragen und den vorgesehenen Platz für unsere verbindlichen Rückgabebedingungen.", "Find the contact for questions and the place for our final returns terms."),
    sections: [
      { title: t("Ihr Anliegen", "Your enquiry"), paragraphs: [t("Für Fragen zu einer Rückgabe oder einem bereits vereinbarten Kauf erreichen Sie uns über das Serviceformular oder per E-Mail. Geben Sie, falls vorhanden, Ihre Bestell- oder Rechnungsnummer an. Eine Begründung für einen gesetzlichen Widerruf ist nicht erforderlich.", "For questions about a return or an existing purchase, use the service form or email. Include an order or invoice reference if available. A reason is not required for a statutory withdrawal.")], action: "returns", email: true },
      { title: t("Rücksendeinformationen", "Return information"), facts: [[t("Rücksendeadresse", "Return address"), t("[Empfänger und vollständige Retourenadresse ergänzen]", "[Add recipient and full return address]")], [t("Rücksendekosten", "Return postage"), t("[Regelung zur Kostentragung ergänzen]", "[Add who pays return postage]")], [t("Retourenablauf", "Return process"), t("[Ablauf und gegebenenfalls Retourenlabel ergänzen]", "[Add return process and label information, if applicable]")]], pending: true },
      { title: t("Widerrufsrecht", "Right of withdrawal"), paragraphs: [t("Die gesonderte Widerrufsseite enthält die vorbereitete Struktur für Belehrung und Musterformular. Sie ist bis zur Ergänzung der Unternehmens- und Vertragsdaten ausdrücklich ein Entwurf.", "The separate withdrawal page contains the prepared structure for the notice and model form. It remains explicitly a draft until company and contract details are completed.")], link: "withdrawal" },
    ],
  },
  {
    id: "sizing", path: "/service/groessenberatung", group: "service", number: "04",
    label: t("Größenberatung", "Size advice"), title: t("Die richtige Größe. Ihr Gefühl.", "The right size. Your feeling."),
    intro: t("Ein guter Sitz beginnt mit ein paar einfachen Angaben. Wir helfen Ihnen bei der Auswahl.", "A comfortable fit starts with a few simple details. We will help you choose."),
    sections: [
      { title: t("Feel Shoes und Loafer", "Feel shoes and loafers"), paragraphs: [t("Messen Sie beide Füße im Stehen von der Ferse bis zum längsten Zeh. Notieren Sie die Länge in Zentimetern und nennen Sie uns Ihre übliche Schuhgröße sowie das gewünschte Modell. Eine persönliche Empfehlung ersetzt keine verbindliche Maßtabelle des Herstellers.", "Measure both feet while standing, from heel to longest toe. Note the length in centimetres and tell us your usual size and the style you are considering. Personal advice does not replace a verified manufacturer size chart.")], list: [t("WAI wird im aktuellen Sortiment in Doppelgrößen von 36/37 bis 46/47 geführt. Die Auswahl auf der Produktseite zeigt die hinterlegten Größen je Variante.", "The current WAI range uses paired sizes from 36/37 to 46/47. The product page shows the sizes listed for each variant."), t("Bei Vehon richtet sich die Größenauswahl nach dem jeweiligen Modell. Eine verlässliche Umrechnung in Zentimeter liegt noch nicht vor.", "Vehon size choices depend on the style. A verified conversion to centimetres is not yet available.")] },
      { title: t("Strick und Passform", "Knitwear and fit"), paragraphs: [t("Vergleichen Sie mit einem Pullover, der Ihnen gut passt: flach hinlegen und Brustweite, Rückenlänge und Ärmellänge messen. Teilen Sie uns die Maße und Ihre bevorzugte Passform mit.", "Compare with a sweater that fits you well: lay it flat and measure the chest width, back length and sleeve length. Share those measurements and your preferred fit."), t("Montechiaro ist im aktuellen Sortiment mit den Größen S bis XXL hinterlegt. Die verbindlichen Maße pro Modell werden noch ergänzt; wir leiten daraus keine pauschalen Körpermaße ab.", "The current Montechiaro range lists sizes S to XXL. Verified measurements for each style are still to be added; we do not infer universal body measurements from those labels.")] },
      { title: t("Modellbezogene Maßtabellen", "Style-specific size charts"), facts: [[t("WAI / Vehon", "WAI / Vehon"), t("[Herstellermaße und Passformhinweise ergänzen]", "[Add manufacturer measurements and fit notes]")], [t("Montechiaro", "Montechiaro"), t("[Brustweite, Rücken- und Ärmellänge je Größe ergänzen]", "[Add chest, back and sleeve measurements per size]")]], pending: true, action: "advice" },
    ],
  },
  {
    id: "fit", path: "/service/passform", group: "service", number: "05",
    label: t("Passform", "Fit"), title: t("So sitzt er richtig.", "How it should fit."),
    intro: t("Barfußschuhe sitzen anders als klassische Schuhe. Woran Sie einen guten Sitz erkennen, bevor Sie anfragen und wenn Sie Ihr Paar zum ersten Mal tragen.", "Barefoot shoes fit differently from conventional shoes. How to recognise a good fit before you enquire and when you first wear your pair."),
    sections: [
      { title: t("Platz für die Zehen", "Room for your toes"), list: [t("Die Zehen liegen flach und können sich frei spreizen.", "Your toes lie flat and can spread freely."), t("Vor dem längsten Zeh bleibt etwas Luft, etwa eine Fingerbreite.", "There is a little space in front of your longest toe, about a finger’s width."), t("Nichts drückt seitlich am Ballen oder am kleinen Zeh.", "Nothing presses on the sides of the ball of your foot or your little toe.")] },
      { title: t("Halt an Ferse und Rist", "Hold at the heel and instep"), list: [t("Die Ferse bleibt beim Gehen ruhig und rutscht nicht heraus.", "Your heel stays in place when you walk and does not slip out."), t("Der Stoff liegt am Rist an, ohne einzuschneiden.", "The fabric sits close over the instep without cutting in.")] },
      { title: t("Richtig messen", "Measuring correctly"), paragraphs: [t("Messen Sie am Nachmittag, im Stehen und an beiden Füßen. Stellen Sie die Ferse an eine Wand, legen Sie ein Blatt Papier darunter und markieren Sie die Spitze des längsten Zehs. Maßgeblich ist der längere Fuß.", "Measure in the afternoon, standing, and on both feet. Place your heel against a wall with a sheet of paper underneath and mark the tip of your longest toe. Go by the longer foot.")], link: "sizing" },
      { title: t("WAI in Doppelgrößen", "WAI in paired sizes"), paragraphs: [t("WAI ist aus elastischem Stoff gefertigt und in Doppelgrößen von 36/37 bis 46/47 erhältlich. Welche Doppelgröße zu welcher Fußlänge passt, ergänzen wir anhand der Herstellermaße. Bis dahin beraten wir Sie gerne persönlich.", "WAI is made from elastic fabric and comes in paired sizes from 36/37 to 46/47. We will add which paired size suits which foot length based on the manufacturer’s measurements. Until then, we are happy to advise you personally.")], facts: [[t("Fußlänge je Doppelgröße", "Foot length per paired size"), t("[Herstellermaße ergänzen]", "[Add manufacturer measurements]")]], pending: true, action: "advice" },
      { title: t("Die ersten Tage", "The first days"), paragraphs: [t("Wenn Sie bisher vor allem gedämpfte Schuhe getragen haben, geben Sie Füßen und Waden Zeit: anfangs kürzer tragen und dann langsam steigern. Bei Schmerzen legen Sie eine Pause ein. Bei bestehenden Fußbeschwerden sprechen Sie vorab mit einer Fachperson.", "If you mostly wear cushioned shoes, give your feet and calves time: wear them for shorter periods at first and build up gradually. Take a break if anything hurts. If you have existing foot problems, speak to a specialist first.")] },
      { title: t("Passt es nicht?", "Not the right fit?"), paragraphs: [t("Schreiben Sie uns. Gemeinsam finden wir eine andere Größe oder ein anderes Modell.", "Get in touch. Together we will find another size or style.")], link: "returns" },
    ],
  },
  {
    id: "care", path: "/service/pflege", group: "service", number: "06",
    label: t("Material & Pflege", "Materials & care"), title: t("Lange Freude. Gute Pflege.", "Lasting enjoyment. Thoughtful care."),
    intro: t("Materialien verdienen unterschiedliche Aufmerksamkeit. Das Pflegeetikett Ihres konkreten Produkts hat dabei immer Vorrang.", "Different materials need different attention. Always follow the care label on your particular product."),
    sections: [
      { title: t("Vor der ersten Reinigung", "Before the first clean"), paragraphs: [t("Prüfen Sie Faserzusammensetzung, Pflegesymbole und Herstellerhinweise. Bezeichnungen wie Denim, Velvet oder Jacquard beschreiben nicht allein die vollständige Materialzusammensetzung und erlauben keine sichere Aussage zur Waschbarkeit.", "Check the fibre composition, care symbols and manufacturer guidance. Descriptions such as denim, velvet or jacquard do not by themselves identify the complete composition or establish whether an item is washable.")] },
      { title: t("Strick aufbewahren", "Storing knitwear"), paragraphs: [t("Wollstrick wird am besten gefaltet gelagert. Wenn das Etikett eine Wäsche erlaubt, richten sich Waschverfahren und Temperatur nach diesen Angaben; Wollstrick wird üblicherweise liegend getrocknet. Die genaue Pflege hängt von der Faserzusammensetzung ab.", "Wool knitwear is best stored folded. If washing is permitted by the label, follow its method and temperature instructions; wool knitwear is usually dried flat. The exact care depends on the fibre composition.")], sources: [{ label: t("Wollpflege bei Woolmark", "Wool care at Woolmark"), href: "https://www.woolmark.com/care/care-for-wool/" }] },
      { title: t("Textile Schuhe", "Textile footwear"), paragraphs: [t("Für WAI und Vehon gelten die Hinweise des jeweiligen Herstellers. Solange uns für Ihr Modell keine bestätigte Reinigungsanleitung vorliegt, geben wir keine pauschale Freigabe für Waschmaschine, Trockner oder Reinigungsmittel. Fragen Sie uns vor einer Behandlung.", "Follow the guidance from the manufacturer for each WAI and Vehon style. Until we have verified instructions for your model, we do not recommend a washing machine, tumble dryer or cleaning product. Ask us before treating the material.")], action: "advice" },
      { title: t("Materialangaben je Modell", "Materials by style"), paragraphs: [t("Auf den Produktseiten finden Sie die bisher hinterlegten Materialbezeichnungen. Vollständige Faseranteile und bestätigte Pflegehinweise ergänzen wir anhand der Herstellerunterlagen.", "Product pages show the material descriptions currently available. Complete fibre percentages and verified care instructions will be added from manufacturer documentation.")], link: "sizing" },
    ],
  },
  {
    id: "faq", path: "/service/faq", group: "service", number: "07", faq: true,
    label: t("Häufige Fragen", "FAQ"), title: t("Ihre Fragen. Unsere Antworten.", "Your questions. Our answers."),
    intro: t("Kurze Antworten zu Feel Shoes, Passform, Anfrage und Pflege. Fehlt etwas? Schreiben Sie uns.", "Short answers about feel shoes, fit, enquiries and care. Something missing? Get in touch."),
    sections: [
      { title: t("Was ist ein Feel Shoe?", "What is a feel shoe?"), paragraphs: [t("WAI-Schuhe bestehen aus nahtlosem, elastischem Stoff. Die flexible Sohle aus recyceltem PU wird mit der CCT-Technologie des Herstellers direkt aufgespritzt. So bleibt der Schuh leicht und lässt sich falten.", "WAI shoes are made from seamless, elastic fabric. The flexible recycled-PU sole is over-injected directly onto it using the manufacturer’s CCT technology. This keeps the shoe light and foldable.")] },
      { title: t("Wofür eignen sich WAI-Schuhe?", "What are WAI shoes made for?"), paragraphs: [t("Die Sport-Modelle (Sport Low, Sport High, Sport Slip-on) sind laut Hersteller für Pilates, Fitness, Aqua-Training und den Strand gedacht. Die Lifestyle-Modelle (Mocassin, Slip-on, High) für Zuhause und unterwegs, etwa im Flugzeug, im Hotel oder auf dem Boot.", "According to the manufacturer, the sport styles (Sport Low, Sport High, Sport Slip-on) are made for pilates, fitness, aqua training and the beach. The lifestyle styles (Mocassin, Slip-on, High) are for home and on the go, such as on the plane, in the hotel or on a boat.")] },
      { title: t("Welche Größe soll ich wählen?", "Which size should I choose?"), paragraphs: [t("Messen Sie Ihre Fußlänge und prüfen Sie unseren Passform-Guide. Wenn Sie unsicher sind, beraten wir Sie persönlich.", "Measure your foot length and check our fit guide. If you are unsure, we will advise you personally.")], link: "fit" },
      { title: t("Was bedeuten Größen wie 40/41?", "What do sizes like 40/41 mean?"), paragraphs: [t("WAI wird in Doppelgrößen gefertigt: Eine 40/41 steht für die Größen 40 und 41. Liegen Sie dazwischen oder sind Sie unsicher, helfen wir Ihnen weiter.", "WAI comes in paired sizes: a 40/41 covers sizes 40 and 41. If you are in between or unsure, we are happy to help.")], action: "advice" },
      { title: t("Gibt es die Modelle für Damen und Herren?", "Are the styles for women and men?"), paragraphs: [t("WAI und die Montechiaro-Pullys führen wir für Damen und Herren. Die Vehon-Modelle sind in den Größen 38 bis 46 erhältlich.", "We carry WAI and the Montechiaro pullys for women and men. Vehon styles are available in sizes 38 to 46.")] },
      { title: t("Kann ich WAI waschen?", "Can I wash WAI?"), paragraphs: [t("Laut Hersteller sind WAI-Schuhe maschinenwaschbar; ein Care Bag liegt bei. Beachten Sie die Hinweise auf dem Etikett Ihres Paares.", "According to the manufacturer, WAI shoes are machine washable and come with a care bag. Follow the label on your pair.")], link: "care" },
      { title: t("Ist meine Anfrage eine Bestellung?", "Is my enquiry an order?"), paragraphs: [t("Nein. Über den Warenkorb fragen Sie Ihre Auswahl unverbindlich an. Wir bestätigen Verfügbarkeit, Versand und Gesamtpreis persönlich.", "No. From your bag you send a non-binding enquiry. We personally confirm availability, shipping and the total price.")], link: "shipping" },
      { title: t("Warum steht bei manchen Modellen „Preis auf Anfrage“?", "Why do some styles say “Price on request”?"), paragraphs: [t("Für diese Modelle bestätigen wir den Preis in Ihrem persönlichen Angebot.", "For these styles, we confirm the price in your personal offer.")] },
      { title: t("Und wenn es nicht passt?", "What if it does not fit?"), paragraphs: [t("Schreiben Sie uns über das Serviceformular. Die verbindlichen Rückgabebedingungen ergänzen wir vor dem Verkaufsstart.", "Contact us through the service form. We will add the binding returns terms before sales launch.")], link: "returns" },
    ],
  },
  {
    id: "imprint", path: "/rechtliches/impressum", group: "legal", label: t("Impressum", "Legal notice"), title: t("Impressum.", "Legal notice."),
    intro: t("Angaben zum Betreiber dieser Website und zu Ihrer Kontaktaufnahme.", "Information about the operator of this website and how to contact us."), draft: true,
    sections: [
      { title: t("Anbieter", "Provider"), facts: [[t("Firma & Rechtsform", "Company & legal form"), t("[Vollständigen Firmennamen und Rechtsform ergänzen]", "[Add full company name and legal form]")], [t("Geschäftsanschrift", "Business address"), t("[Straße, Hausnummer, PLZ, Ort und Land ergänzen]", "[Add street, postcode, city and country]")], [t("Vertretung", "Representative"), t("[Vertretungsberechtigte Person ergänzen]", "[Add authorised representative]")]], pending: true },
      { title: t("Kontakt", "Contact"), email: true, facts: [[t("Telefon", "Phone"), t("[Telefonnummer ergänzen]", "[Add telephone number]")]], pending: true },
      { title: t("Register & weitere Angaben", "Registration & further details"), facts: [[t("Register", "Register"), t("[Register und Registernummer, soweit zutreffend]", "[Register and number, where applicable]")], [t("Umsatzsteuer-ID / UID", "VAT ID"), t("[Umsatzsteuer-ID, soweit vorhanden]", "[VAT ID, where applicable]")], [t("Berufs- und Aufsichtsangaben", "Professional & supervisory details"), t("[Nach Firmensitz und Tätigkeit prüfen und ergänzen]", "[Review and add based on registered location and business activity]")]], pending: true },
    ],
  },
  {
    id: "privacy", path: "/rechtliches/datenschutz", group: "legal", label: t("Datenschutz", "Privacy"), title: t("Ihre Daten. Verständlich erklärt.", "Your data. Clearly explained."),
    intro: t("Welche Daten bei NES verarbeitet werden, welche Funktionen auf Ihrem Gerät speichern und wie Sie uns erreichen.", "What NES processes, which features store information on your device and how to get in touch."), draft: true,
    sections: [
      { title: t("Verantwortlicher", "Controller"), paragraphs: [t("[Firmenname, vollständige Anschrift und Land des Verantwortlichen ergänzen]. Für Datenschutzanfragen erreichen Sie uns über die folgende Adresse.", "[Add the controller’s company name, full address and country]. You can contact us about privacy at the address below.")], email: true },
      { title: t("Website und Hosting", "Website and hosting"), paragraphs: [t("Die Website ist für den Betrieb über Cloudflare Pages vorgesehen. Beim Abruf werden technische Verbindungsdaten wie IP-Adresse, Zeitpunkt und angefragte Adresse verarbeitet, um Inhalte auszuliefern und den Betrieb abzusichern. Die endgültigen Angaben zu Vertragspartner, Speicherfristen und gegebenenfalls internationalen Datenübermittlungen werden für die tatsächliche Hosting-Konfiguration ergänzt.", "The website is prepared for hosting on Cloudflare Pages. Requests involve technical connection data such as IP address, time and requested URL to deliver content and secure the service. Final details of the provider, retention periods and any international transfers will be completed for the actual hosting configuration.")] },
      { title: t("Speicherungen auf Ihrem Gerät", "Storage on your device"), paragraphs: [t("Warenkorb, Merkliste und eine von Ihnen gewählte Sprache werden ausschließlich für die jeweilige Funktion im lokalen Browserspeicher abgelegt. Leere Listen werden nicht gespeichert. Diese Einträge enthalten keine E-Mail-Adresse und werden nicht als Besucherkennung an einen Analysedienst gesendet.", "Your bag, saved items and a language you choose are stored locally in your browser for those features. Empty lists are not stored. These entries contain no email address and are not sent to an analytics service as visitor identifiers.")], storage: true },
      { title: t("Darstellung, Navigation und Vorschauen", "Display, navigation and previews"), paragraphs: [t("Die verwendeten Schriftdateien werden von dieser Website ausgeliefert. Für die Schriften wird keine Verbindung zu Google aufgebaut. Scrollpositionen und geöffnete Abschnitte können im Verlauf des aktuellen Tabs gemerkt werden, damit die Zurück-Navigation an die richtige Stelle führt.", "Font files are served by this website. Loading fonts does not connect to Google. Scroll positions and expanded sections can be remembered in the current tab’s history so that back navigation restores your place."), t("Das Society-Popup und der ausdrücklich als Demo markierte Checkout übermitteln keine Anmeldung, Zahlung oder Bestellung. Eine im Society-Popup eingegebene E-Mail bleibt nur bis zum Abschluss oder Schließen in dessen Arbeitsspeicher. Der Anzeigestatus des Popups wird nur für die laufende Seite gemerkt.", "The Society invitation and the checkout explicitly marked as a demo do not submit a subscription, payment or order. An email entered into the Society popup stays only in its temporary memory until completion or closure. The popup’s display state is remembered only for the current page session.")] },
      { title: t("Kontakt- und Beratungsanfragen", "Contact and advice enquiries"), paragraphs: [t("Wenn Sie ein Formular absenden, werden Ihre Angaben zur Bearbeitung der Anfrage übermittelt. Dazu gehören Name, E-Mail-Adresse, Nachricht und je nach Formular Angaben zu Unternehmen, Produkt oder Auswahl. Die vorbereitete Verarbeitung nutzt Cloudflare D1 zur Speicherung und Resend für die Benachrichtigung per E-Mail. Zusätzlich können Eingangszeit, Formularherkunft, Sprache und Bearbeitungsstatus gespeichert werden.", "Submitting a form sends your details to handle the enquiry, including name, email address, message and, depending on the form, company, product or selection details. The prepared integration uses Cloudflare D1 for storage and Resend for email notifications. Receipt time, form source, language and processing status may also be recorded."), t("[Die zutreffenden Rechtsgrundlagen, Empfänger, Löschfristen und gegebenenfalls Übermittlungsgarantien für den tatsächlichen Betrieb ergänzen]. Es ist derzeit keine automatische Löschfrist in der Anwendung eingerichtet.", "[Add the applicable legal bases, recipients, retention periods and any transfer safeguards for the actual operation]. The application currently has no automatic deletion schedule.")] },
      { title: t("E-Mail-Kontakt", "Email contact"), paragraphs: [t("Nachrichten an unsere Kontaktadresse und Antworten auf Benachrichtigungen werden im E-Mail-Postfach bearbeitet. Laut aktueller Einrichtung wird dieses Postfach von Hostinger bereitgestellt. [Anbieter-Vertragspartner, Rechtsgrundlage, Aufbewahrungsfristen und gegebenenfalls Übermittlungsgarantien ergänzen].", "Messages to our contact address and replies to notifications are handled in our email inbox. According to the current setup, this inbox is provided by Hostinger. [Add the provider’s legal entity, legal basis, retention periods and any transfer safeguards].")] },
      { title: t("Newsletter", "Newsletter"), paragraphs: [t("Das Newsletterformular am Seitenende ist von der Society-Demo getrennt. Die vorbereitete Anmeldung sendet zunächst eine Bestätigungs-E-Mail. Erst nach Bestätigung wird die Adresse als angemeldet geführt. Gespeichert werden E-Mail-Adresse, Sprache, Anmeldequelle, Status und Zeitpunkte sowie gehashte Bestätigungs- und Abmeldetokens. Bestätigungslinks sind 24 Stunden gültig.", "The newsletter form near the page footer is separate from the Society demo. The prepared signup flow first sends a confirmation email; the address becomes subscribed only after confirmation. Stored data includes email address, language, signup source, status, timestamps and hashed confirmation and unsubscribe tokens. Confirmation links are valid for 24 hours."), t("Der Versand ist über Resend und die Speicherung über Cloudflare D1 vorbereitet. Eine Abmeldung erfolgt über den Abmeldelink. Dabei wird der Status geändert; der Datensatz wird nicht automatisch gelöscht. [Einwilligungstext, Aufbewahrungs- und Löschkonzept sowie Anbietervereinbarungen für den Live-Betrieb ergänzen].", "Delivery is prepared through Resend and storage through Cloudflare D1. Unsubscribing uses the unsubscribe link and changes the status; it does not automatically erase the record. [Complete consent wording, retention and deletion policies and provider agreements for live operation].")] },
      { title: t("Analyse, Werbung und Cookies", "Analytics, advertising and cookies"), paragraphs: [t("Im derzeitigen Website-Code sind keine Analyse-Pixel, Werbe-Tracker oder Marketing-Cookies eingebunden. Ein pauschales Einwilligungsbanner wird deshalb nicht angezeigt. Zusätzliche Dienste und Einstellungen des Hosting-Anbieters müssen vor dem Live-Betrieb gesondert geprüft werden. Einwilligungspflichtige Dienste dürfen erst nach entsprechender Zustimmung aktiviert werden.", "The current website code contains no analytics pixels, advertising trackers or marketing cookies, so a blanket consent banner is not shown. Additional services and hosting settings must be reviewed separately before live operation. Services requiring consent must only be activated after that consent.")] },
      { title: t("Ihre Rechte und Kontakt", "Your rights and contact"), paragraphs: [t("Sie können nach Maßgabe der gesetzlichen Voraussetzungen Auskunft, Berichtigung, Löschung, Einschränkung und Datenübertragbarkeit verlangen sowie Widerspruch einlegen. Eine erteilte Einwilligung können Sie für die Zukunft widerrufen. Außerdem besteht ein Beschwerderecht bei einer Datenschutzaufsichtsbehörde. [Zuständige Aufsichtsbehörde nach Festlegung des Verantwortlichen ergänzen].", "Subject to the applicable legal conditions, you may request access, correction, deletion, restriction and portability, and object to processing. You may withdraw consent for the future and complain to a data protection authority. [Add the relevant authority once the controller is confirmed].")], email: true },
    ],
  },
  {
    id: "terms", path: "/rechtliches/agb", group: "legal", label: t("AGB", "Terms & conditions"), title: t("Allgemeine Geschäftsbedingungen.", "Terms & conditions."),
    intro: t("Die Struktur für unsere künftigen Verkaufsbedingungen. Dieser Entwurf ist noch keine abschließende Vertragsgrundlage.", "The structure for our future sales terms. This draft is not yet a final contractual document."), draft: true,
    sections: [
      { title: t("Anbieter und Geltungsbereich", "Provider and scope"), paragraphs: [t("[Vertragspartner mit vollständigen Unternehmensdaten, Zielgruppe, Liefergebiet und Vertragssprachen ergänzen].", "[Add the contracting party’s full details, customer group, delivery territory and contract languages].")] },
      { title: t("Vertragsschluss", "Formation of contract"), paragraphs: [t("Aktuell ist die Auswahl-Anfrage unverbindlich. Die Checkout-Demo löst keine Bestellung aus. [Vor Aufnahme eines echten Bestellbetriebs Annahmeverfahren, Vertragsspeicherung und Korrekturmöglichkeiten festlegen].", "Selection enquiries are currently non-binding. The checkout demo does not place an order. [Before enabling orders, specify acceptance, contract storage and correction options].")] },
      { title: t("Preise, Zahlung und Lieferung", "Prices, payment and delivery"), paragraphs: [t("[Steuerangaben, Zahlungsarten, Fälligkeit, Versandkosten, Lieferzeiten und Umgang mit Nichtverfügbarkeit verbindlich ergänzen].", "[Add binding tax information, payment methods, due dates, shipping costs, delivery times and availability terms].")], link: "shipping" },
      { title: t("Widerruf und gesetzliche Rechte", "Withdrawal and statutory rights"), paragraphs: [t("[Zutreffende Widerrufsbelehrung und Informationen zur gesetzlichen Gewährleistung ergänzen. Freiwillige Garantien nur bei tatsächlichem Bestehen aufnehmen].", "[Add the applicable withdrawal notice and statutory warranty information. Include voluntary guarantees only where they actually exist].")], link: "withdrawal" },
      { title: t("Weitere Vertragsangaben", "Further contractual information"), paragraphs: [t("[Erforderliche Angaben zu Beschwerdeverfahren, gegebenenfalls Streitbeilegung und weiteren zulässigen Vertragsbedingungen nach Firmensitz und Zielmarkt rechtlich prüfen und ergänzen].", "[Review and complete complaints handling, any applicable dispute resolution details and other lawful terms based on the company’s location and target market].")] },
    ],
  },
  {
    id: "withdrawal", path: "/rechtliches/widerruf", group: "legal", label: t("Widerrufsrecht", "Right of withdrawal"), title: t("Widerruf. Klar geregelt.", "Withdrawal. Clearly explained."),
    intro: t("Vorbereitete Struktur für Widerrufsbelehrung und Musterformular. Die verbindliche Fassung folgt mit den vollständigen Unternehmens- und Verkaufsdaten.", "Prepared structure for the withdrawal notice and model form. The binding version will follow once company and sales details are complete."), draft: true,
    sections: [
      { title: t("Widerrufsbelehrung", "Withdrawal notice"), paragraphs: [t("[Die für die tatsächlichen Warenverkäufe an Verbraucher passende gesetzliche Musterbelehrung mit Fristbeginn, Erklärungsempfänger und Folgen des Widerrufs vollständig einsetzen].", "[Insert the full statutory model notice applicable to the actual consumer goods sales, including when the period begins, the recipient and the effects of withdrawal].")], facts: [[t("Empfänger", "Recipient"), t("[Firma und vollständige Anschrift ergänzen]", "[Add company and full address]")], [t("Rücksendekosten", "Return costs"), t("[Zutreffende Regelung ergänzen]", "[Add applicable terms]")]], pending: true },
      { title: t("Muster-Widerrufsformular", "Model withdrawal form"), paragraphs: [t("[Gesetzliches Musterformular mit vollständigen Empfängerdaten ergänzen und als speicherbare Fassung bereitstellen]. Für die Zuordnung einer Erklärung sind Angaben zur Person, zu den Waren und zum Vertrag hilfreich.", "[Add the statutory model form with full recipient details and provide a downloadable version]. Customer, product and contract details help identify a declaration.")] },
      { title: t("Online-Widerrufsfunktion", "Online withdrawal function"), paragraphs: [t("Die gesetzlich erforderliche Online-Widerrufsfunktion wird zusammen mit einem echten Online-Bestellprozess eingerichtet. Der aktuelle Demo-Checkout schließt keinen Vertrag und nimmt keine Zahlung entgegen. Dieser Hinweis ersetzt keine Widerrufsbelehrung für einen tatsächlich geschlossenen Kaufvertrag.", "The legally required online withdrawal function will be implemented alongside a real online ordering process. The current demo checkout concludes no contract and takes no payment. This notice does not replace the withdrawal notice for an actual purchase contract.")] },
      { title: t("Kontakt für bestehende Anliegen", "Contact for existing enquiries"), paragraphs: [t("Wenn Sie bereits einen Kauf persönlich mit NES vereinbart haben, können Sie uns dazu per E-Mail kontaktieren. Bitte nennen Sie zur Zuordnung die betroffenen Artikel und, soweit vorhanden, die Bestell- oder Rechnungsnummer.", "If you have already agreed a purchase directly with NES, contact us by email. Please identify the items and, if available, include an order or invoice reference.")], email: true, link: "returns" },
    ],
  },
];

export function getServicePage(pathname) {
  const path = pathname.replace(/\/$/, "");
  return SERVICE_PAGES.find((page) => page.path === path) || null;
}
